[build]
  publish = "."

[[redirects]]
  from = "/abdelaziz"
  to = "/Abdelaziz-Fitness-Plan/index.html"
  status = 200

[[redirects]]
  from = "/abdelaziz/*"
  to = "/Abdelaziz-Fitness-Plan/:splat"
  status = 200

[[redirects]]
  from = "/abdulrahman"
  to = "/Abdulrahman-Fitness-Plan/index.html"
  status = 200

[[redirects]]
  from = "/abdulrahman/*"
  to = "/Abdulrahman-Fitness-Plan/:splat"
  status = 200
